### ISSUE TITLE
Cal Poly SLO Student: Clarification on Valley Bottom purpose, specific HUC8 vb editing help

### ISSUE THREAD

**Issue by ssuplick** [Riverscapes/pyBRAT#111]
Hi BRAT team! I'm working to finish up a BRAT-based analysis of the Salinas River watershed (central coast of CA) for my senior project/thesis. Seeking advice for valley bottom-editing for its large northern valley bottom, dominated by ag, whose riparian area is severely degraded. I've attached a few example photos for my questions:

**1. Ex: South of Chualar, Google Earth**: looks like there's an abandoned terrace in the left; the right side of the photo is more a human-constructed flood control structure? Is "contemporary floodplain" where the river might flood to without current flood control measures, or where it's likely currently constrained because of them?
![south_of_chualar_edited](https://user-images.githubusercontent.com/41078486/42527314-1eef006a-842d-11e8-9968-21d034c55f7b.jpg)
**2. VBET output on perennial stream network**: should I create separate polygons, or connect the "broken" perennial reaches as one valley bottom polygon? E.g. connect San Lorenzo Creek to Salinas River near King City. (It is common to have sporadic perennial reaches in this HUC8, as the Salinas River  has a good deal of subsurface flow throughout the year.) Could the DAC help here?

![salinas_river_vbet_output_semiedited_w_question_example_area](https://user-images.githubusercontent.com/41078486/42527313-1ed6e020-842d-11e8-8268-e6c6cc494430.PNG)
![question_example_area_toporeference](https://user-images.githubusercontent.com/41078486/42527312-1ebea1c2-842d-11e8-9419-251e83f98d44.PNG)
![question_example_area](https://user-images.githubusercontent.com/41078486/42527311-1ea78726-842d-11e8-9bfb-12e00244bdb4.PNG)

**3. Confused on purpose of the Valley Bottom polygon, in general, with how BRAT operates?**
**4. 3rd party verification possible if I send my final valley bottom to you?** (No worries if not, I know you are all super busy).

**Best future communication?** Also, I've currently been in contact with Ms. Bangen. However, based on recent activity it looks like BRAT development is really taking off! So I understand that all of you are likely swamped right now. Would the GitHub Issues forum thus be a better communication tool, as it'll enable flexibility on who can respond or is the best person to respond for the given question? Or is one contact person preferred? Thanks for your time!
-Stuart (recent Cal Poly environmental management grad)

**Comment by wally-mac** [comment]
@Albonicomt, when you return from vacation can you please address Stuart's issue?  Thanks

**Comment by Albonicomt** [comment]
@ssuplick 
**1.** In my opinion I believe it would be best to call the "contemporary floodplain" where the river would flood without current flood control measures. Unless it is absolutely obvious that the floodplain can not reach its extent in your investigation when editing the Valley Bottom. As long as you are consistent and have a good argument for your reasoning, I would go with that. Since Valley bottom editing of a particular watershed takes such a vast majority of your time, I wouldn't stress on details as much and go for a broader overall picture of the Watershed's contemporary floodplain.  
**2.** In this case, I would connect the Valley Bottom from San Lorenzo Creek to the Salinas River Valley Bottom. Not sure what DAC is?
**3.** So in general, the valley bottom is the extent at which BRAT reads all of the input layers: Vegetation, Roads, Canals, Railroads, and Land Use. It serves as the boundary to what the BRAT tool takes into account when calculating all the outputs. 
**4** Sure, I can give your Valley Bottom a quick scan and point out some issues if I see any. 

For further contact: Github works well or If you need to reach me for further questions, my email is Ma697@nau.edu and if you want to chat on the phone: 505-239-4916.

**Comment by ssuplick** [comment]
@Albonicomt ah! All that would make sense. A few follow-ups:
1. Would you recommend being more liberal then and going for the "mega flood level" floodplain? E.g. there are some smaller terraces to the east of the King City area that you can see in Google Earth and to a smaller extent in the DEM, but these occur before the alluvial fan/foothill edges that mark the valley bottom extent for other, more confined stream reaches in the HUC8. Still, considering the current vegetative boundaries of the riparian area, and the infrequency of "mega floods" due to watershed dams and low rainfall, I have a hard time wrapping my head around the possibility that the contemporary floodplain could extent out to the foothills.
2. DAC refers to the Drainage Area Check; I don't think it's actually relevant here. (http://brat.riverscapes.xyz/Documentation/Tutorials/StepByStep/3.1-DrainageAreaCheck.html - "Stream networks often don’t align with the flow of Flow Accumulation rasters, leading to misleading or obviously false results. The DAC is meant to check for cases where the stream network misses the flow accumulation line, based on the assumption that the stream will always have a higher DA value as it goes downstream.")
4. Great. I'll try to send it by email by the end of this weekend.
Thanks so much once again!
