### ISSUE TITLE
Updating previous runs of BRAT: Middle Bear BRAT

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#124]
@wally-mac @joewheaton 
I am gathering information together for the NRCS workshop coming up in Logan in September which ties into what we discussed in the meeting today about being able to use these older versions of BRAT runs and updating them in order to produce many of the new outputs that are included in BRAT which includes developments that have been made by @banderson1618 and @bangen. 
For my focus I am looking at Station creek, Birch Creek, and 3 mile Creek to create RCAT and BRAT outputs for them. @Albonicomt has done a great job of running BRAT on the Middle Bear in Idaho which will include the Birch Creek BRAT portion of the project. This data and metadata is included at the following link [here](https://usu.box.com/s/bmm4nfh2yk1aklxr48f734xrv41br6c8). It was ran on 6/5/2018 and does not include the intermediates, layer packages for the shapefiles, improved restoration model and v2 restoration model. 
Concerning this previous version of BRAT and the things which are missing from the project folder is it worth using the inputs and rerunning a new product through the updated BRAT or just certain scripts of  BRAT?
I am leaning on your input on this. What I think would be a minimum of what would need to be ran with the new version of BRAT would be the...

- Layer Package Generator( which would take the layers and create a layer package(I do not know if I would have to rerun any other steps to get the individual layers to appear?)) 

- Step 7 and 7.1(which would produce new outputs for the restoration model)

- Is there more to it than that @banderson1618 @bangen?

I will be messing around with it to see what I can accomplish in the meantime.

**Comment by bangen** [comment]
@MatthewMeier did @wally-mac or @joewheaton get back to you about this?

In reference to the layer package generator.  @banderson1618 creates the individual symbology layer files when they are loaded or created.  For example, the individual input layer symbology files (e.g., roads, canals) are created when the BRAT Project tool is run whereas the slope layer symbology file is created in the BRAT Table tool (since this is where the slope raster is created).  So, long story short, in order to have the 'correct' symbology layer files for the layer package generator you would need to re-run the entire tool.  @wally-mac and @joewheaton I see this as a current limitation for generating layer packages for older runs of BRAT.  IMO, it would be nice to have an optional 'manual' version of the layer package generator where the user could point to all of the requisite individual feature classes/rasters/etc and have layer files created rather than having to re-run the tool.  Thoughts?

**Comment by MatthewMeier** [comment]
@bangen I thought as much because there were so many new features for the outputs and so I have been working on rerunning it. The only thing I am worried about it having it run once and then by the time the workshop is there will be a new and better version to run it through again. I guess it is not the worst thing in the world.

**Comment by wally-mac** [comment]
@bangen, I like your idea of  "an optional 'manual' version of the layer package generator where the user could point to all of the requisite individual feature classes/rasters/etc and have layer files created rather than having to re-run the tool. " @joewheaton what are your thoughts on this?

**Comment by joewheaton** [comment]
I'm closing this for now. We do need to revisit all of these NRCS runs to repackage, but we will do those as new Analysis tickets assigned to specific people.
