### ISSUE TITLE
TNC NHD network issue

### ISSUE THREAD

**Issue by CHafen** [Riverscapes/pyBRAT#126]
I ran into some issues while editing the TNC HUC 8 "Russian." There sections throughout the HUC 8 where there are gaps in the full network NHD Flowline even though from looking at the imagery there is clearly a stream/river there. So, the edited perennial network also has gaps that I can't add sections in because they are missing from the full network. 
Wally suggested contacting the NHD people to make them aware of this issue. So, I will try and contact them about it.
Any other suggestions on dealing with this issue? Has any one else seen some thing like this before? I know  I've seen other networks that maybe had a couple spots that might have been missing some flowlines, but nothing with any where close to as many holes as this one has (seen attached images).

Image legend:
blue lines- perennial network
grey lines- full network
red circles- area that should but do not have an NHD flowline
![tnc_example3](https://user-images.githubusercontent.com/39837888/43218995-f4a3e378-8ffa-11e8-8a77-ea7c0ebb054b.PNG)
![tnc_example1](https://user-images.githubusercontent.com/39837888/43218996-f4baa8ec-8ffa-11e8-9276-0b94eb6fc760.PNG)
![tnc_example2](https://user-images.githubusercontent.com/39837888/43218997-f4d098fa-8ffa-11e8-8c2c-215620d89dfd.PNG)

**Comment by bangen** [comment]
I'm appending @MatthewMeier and @wally-mac responses below.

As Wally suggested, it would be good to pass this info along to folks at the USGS.  I've also seen some gaps in networks but not to this extent.  We know there are limitations and errors in regional datasets such as NHD data.  That being said, I don't think we should go to the trouble of filling in the missing lines since we are pretty upfront about the limitations with folks and the Russian isn't one of our priority basins for this project.  Thoughts @wally-mac ?

_Chalese,
I have had some circumstances like this as well and just assumed there was nothing that I could do as well. there are a lot of holes in that one though for sure. The challenge that I see with manually adding those line segments in would be that the whole point of us using the nhd flow lines so that they are already put together and transferable to other people that are using other data sets that people have constructed from nhd flow lines. If anyone else has contradicting input let us know.
Thanks
Matt_

_Thanks for the heads up. I personally have not seen this before.  I suggest that we make it an issue on GitHub.  Also, it might be worth contacting the NHD folks and let them know what you found.  Are on on GitHub yet? If not you can join here: https://github.com/
Once you have a username please let me know what it is and I can send you collaboration invites. 
Cheers,
Wally_

**Comment by CHafen** [comment]
Thanks for the feedback. I figured we probably didn't want to fill in the missing segments but wanted to make sure I was right on that. And also wanted to make people aware that this one is going to be messy because of the missing sections. It's a bit of a headache to edit because it is hard to tell where I can actually make edits. But, I will do the best I can with it without taking too long on it.

Thanks!

**Comment by CHafen** [comment]
Before contacting the USGS folks about this I decided to download the NHD network from the data gateway just to check and see if something happened with the file that was making it have the gaps and the flowline I got from that is completely different than the one I got off of Box. It still has some gaps, but not as bad, but also the NHD area is a little different in some places and the flowline through the NHD area is also different to match it. So, I'm not going to worry about contacting the USGS about it since the one I got from data gateway looks a lot better. 
Is it possible that the NHDFlowline on Box is old? 
Should we just stick with what we have now or do you want to update it with the better NHD that doesn't have so many gaps? 
What are your thoughts @wally-mac @bangen ?
