### ISSUE TITLE
What are the cutoff values for the iHyd_SP2

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#148]
@joewheaton @bangen @banderson1618 I have been working on some deliveragbles for BRAT and looking over the data with @wally-mac. Consult the following [video...](https://youtu.be/UL2pLWv2Slk)
After the discussion that was lead between the two of us @wally-mac suggests that he would like to see that the Logan river have less capacity than what we are seeing the model predict. He describes a rare to none scenario occurring more often.  If there are any insights into this please share and contribute.
Thank you all for the help.
Matt

**Comment by bangen** [comment]
@MatthewMeier and @wally-mac 

The current Q2 streampower MFs are:

```   
sp2['persists'] = fuzz.trapmf(sp2.universe, [0, 0, 1000, 1200])
sp2['breach'] = fuzz.trimf(sp2.universe, [1000, 1200, 1600])
sp2['oblowout'] = fuzz.trimf(sp2.universe, [1200, 1600, 2400])
sp2['blowout'] = fuzz.trapmf(sp2.universe, [1600, 2400, 10000, 10000])
```

So under the current model, a Q2 streampower of ~800 watts (the value you were showing in the video) alone wouldn't result in there being a lower capacity estimate.  In fact, we don't have a 'trump' rule whereby a high (or 'blowout') streampower value results in a capacity of 'none' or 'rare'.

Without more information it's pretty difficult for me to pinpoint what exactly is driving your higher than expected capacity estimates on the Logan.  You mentioned it isn't veg.  The other inputs to the combined capacity model are low flow streampower, Q2 streampower and slope.  So without knowing more, the discrepancies that you're seeing between the statewide and more recent run could be due to any one of these.

My initial questions for troubleshooting are:

- What version of BRAT was used on the statewide run?
- Are you using the exact same flow equations that were used in the statewide run?
- Are the Q2 estimates different for the reaches you've flagged?
- Are the reach slopes different for the reaches you've flagged?  Reach slope is both an input to the combined capacity model AND the streampower calculation.  So if these are different between the models than this could be driving things.

**Comment by bangen** [comment]
Closing.
