### ISSUE TITLE
Cluster maximum size?

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#150]
@banderson1618 
@wally-mac and I were wondering if you ever looked into creating a maximum cluster size for the Cluster id/braid handler soon to be named the mainstem/anabranch tool? The issue that @Albonicomt and I have seen is that the clusters are being created that encompass a mass area that is labor intensive to edit later on. If there is a way to create a maximum cluster size that would be helpful. @joewheaton or @sshahverdian might have some insights on what would be an appropriate value for this to be given @joewheaton experience with anabranched and multithreaded systems.
Matt

**Comment by banderson1618** [comment]
I've thought about it, but there are some hurdles.

The primary problem is telling a computer where to split the cluster. As humans, we can recognize when a cluster is generally running north-south or east-west, but the program doesn't know intuitively. I can think of some methods to approximate that sort of intuition, but they'd get rough if the direction of the split ever switches (I can describe these better in person with a white board). 

The second problem is that splitting up a cluster wouldn't really cut down on the labor required to find the mainstem. All the streams that were in the cluster would still be in the cluster, they'd just be in different clusters. Splitting the cluster would help if you were worried about an upstream "main channel" reach being given the value of the "main channel" reaches much further down stream, but you would still have to deal with labeling both as "main channel" or "side channel".

I think we should talk about this in person some time, if it's a significant enough issue. I may be misunderstanding the problem, and I can more effectively communicate possible solutions in person. I'm available for the rest of today and tomorrow, if you want. @sshahverdian, @wally-mac and @joewheaton, you'd be free to join us if we decide to meet.

**Comment by bangen** [comment]
@banderson1618 

I took a quick look at the FindBraidedNetwork code.  One potential way to handle the issue that Matt brought up is to calculate the area of the polygons after converting the polylines to 'donut' polygons.  If the area is larger than a certain size threshold then don't flag it as a cluster.  My only question/concern is in the case of multiple potential braids falling within the same donut.  When these are converted to polygons are they represented as a single polygon or multiple?  If it's the latter I'm worried about throwing out 'real' clusters that might exists within a larger 'false' cluster.

**Comment by bangen** [comment]
@banderson1618 @wally-mac 

I'm reopening this issue since we didn't explore a solution.  Considering how big of a time sink identifying main vs side channels can be I think it's worth the time to dig into this further. @banderson1618 if you did look into the above and it didn't lead anywhere feel free to comment here and close the issue.

@banderson1618 I took a look at the braid handler code.  There are a bunch of functions in there and I wasn't able to identify how you are actually identifying clusters.  A few questions/ideas:

- Are you using the feature to polygon tool to identify clusters? 
- It looks like your code merges clusters that are touching(?).  If that's the case once way to avoid some of these 'super clusters' that have been such a headache for folks is to calculate the area of each cluster before merging.  If they're over a certain size, delete them.  Then run the cluster merge function.

**Comment by banderson1618** [comment]
@bangen, I think the only good way to explain how the Braid Handler works would be over a phone call. It's relatively involved, and it would make suggesting solutions easier for you. Let me know when works for you.
