### ISSUE TITLE
BRAT Project Layer and Layer Package Generator Crashed Tool

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#156]
@banderson1618 

Running the BRATProject tool from the 'layer_package_changes' branch was crashing ArcMap (no detailed error message thrown, the program straight crashes).  When I commented out the line to create input layers for 'Veg Type - BPS Class Name' it ran fine.  So something is up with that line of code:

``` # add the historic veg inputs to project
    histVegDestinations = copyMultiInputToFolder(histVegFolder, hist_veg, "Hist_Veg", isRaster=True)
    makeInputLayers(histVegDestinations, "Historic Vegetation Suitability for Beaver Dam Building", symbologyLayer=histVegSuitabilitySymbology, isRaster=True, fileName="HistVegSuitability")
    makeInputLayers(histVegDestinations, "Historic Riparian", symbologyLayer=histRiparianSymbology, isRaster=True, checkField="GROUPVEG")
    makeInputLayers(histVegDestinations, "Veg Type - BPS Type", symbologyLayer=histVegBPSSymbology, isRaster=True, checkField="GROUPVEG")
    # makeInputLayers(histVegDestinations, "Veg Type - BPS Class Name", symbologyLayer=histVegBPSNameSymbology, isRaster=True)
```

After running through the entire BRAT model, I ran the 'Layer Package Generator' tool but ArcMap crashed.  Any hunch why?  Had you gotten it to run successfully before pushing your latest changes on Friday?

**Comment by banderson1618** [comment]
The LPG is now set up to automatically generate any layers that are missing. I'd assume that the same bug that caused it to crash when making the layer in "Make Project" is also making it crash in the LPG.  I've commented out the equivalent code in the LPG and pushed to both the layer_package_changes branch and the new_conflict_model branch, so I'd recommend pulling from both of those.

I'll look more in to why it might be crashing like that, since I've been able to replicate it. I checked that the .tif file had the attribute being symbolized, so it's not that.
