### ISSUE TITLE
RAVE is ready!!!! BRAT is NOT

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#179]
@philipbaileynar just released first version of ArcGIS RAVE add in! 

> The first release of the RAVE AddIn for ArcGIS is available. RAVE displays Riverscapes projects and can build consistent, symbolized ArcMap documents.
> 
> http://rave.riverscapes.xyz/
> 
> Currently RAVE does not ship with any layer symbologies. You can easily set these up yourself using the instructions online. Once the core FHC lab users agree on a common set of symbologies we can take them and include them in the next release of the software.
> 
> The same goes for business logic XML files. The software ships with a somewhat outdated set of business logic XML files. There wasn't one for BRAT, so I threw one together based on the layer packages that I found in Box. These need improving and there's documentation online that lays out the rules for writing your own business logic XML. It's fiddly and some experience with XML is definitely helpful.
> 
However this is the real task here. We URGENTLY need to fix our Riverscapes projects and probably write some scripts that can go through and salvage old projects unless we want to re-run them (which we may).  See @philipbaileynar comment:

> Finally, every BRAT project that I looked at in Box was essentially broken. Most of the file paths were missing or contained placeholder text such as "p" or "f". Before anyone can use these projects with the new RAVE AddIn someone is going to have to go back and fix these BRAT project files. Perhaps even more urgent is fixing the script that generates these project files so that correct paths are generated going forward.

1. So step 1, get one BRAT project that can actually open in BRAT!
2. Step 2, fix BRAT code so all future projects can open.
3. Step 3, plumb in and hook up all your symbology so that RAVE does what the layer package generator does.
4. Step 4, Refine.... 

All the while, improve the [RAVE documentation](http://rave.riverscapes.xyz) and post bugs and questions to [RAVE issue board](https://github.com/Riverscapes/RaveAddIn/issues).

**Comment by banderson1618** [comment]
I've spent the last couple days working on fixing the XML. I have it properly set up to display the Analyses and some of the inputs, but I don't think the current XML setup supports our new category of Intermediates. That will likely take more time to implement. Here's a picture of what RAVE currently displays with a run of what's on the master branch right now:

![rave_example](https://user-images.githubusercontent.com/21353496/46177651-f22d9780-c270-11e8-9760-00c3bdb1fc5a.PNG)

My priority right now is to create the intermediates category on XML, then work on creating a standalone script that replaces the broken XMLs for existing projects. @joewheaton and @wally-mac, does that make sense, or is there something else that should take precedence?

**Comment by philipbaileynar** [comment]
@banderson1618 I can't speak to priorities, but here are the steps to get BRAT working with RAVE.

## 1. Download and Edit BRAT Business Logic XML

Download the existing [brat.xml](https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/XML/brat.xml) business logic XML file and save it in the same folder as a reliable BRAT project that has all the file paths fixed. Start editing this local copy to reflect how you want the project to be displayed in RAVE. Layers are added to the map in the same hierarchy as the project explorer tree, so in essence you want to edit the business logic XML so that it reproduces the same hierarchy as your layer package files.

One quick fix... Notice how the root node in your screenshot says `TITLE_NOT_FOUND`. This is because your project file has an empty `Name` tag near the start. Provide a name here and it will be used as the root node in the tree.

Follow the business logic XML [rules](http://rave.riverscapes.xyz/business-logic.html#business-logic-definition). You can add **Intermediates** with children etc. This will require some trial and error. You can quickly see the affects of your edits by right clicking on the project node in the RAVE Explorer and choosing the **Refresh Project Hierarchy** option. It should immediately detect your business logic revisions and update the tree.

![](http://rave.riverscapes.xyz/assets/images/refresh.png)

## Create Layer Files for Each Dataset Type

The easiest way to do this is to load one of your existing layer package files (I looked at the Nevada one that looks really decent). Right click on each **individual layer** and **Save As Layer File...**. Make sure you name the layer file with the symbology key defined in the business logic XML. You can change these keys to whatever you want, just be really consistent. Think about whether a layer type is specific to BRAT or a more general Riverscapes layer (e.g. DEM). Here are the [instructions](http://rave.riverscapes.xyz/symbology.html#symbology-keys).

## Test Your Fixes

When you are done editing the business logic and generating layer files, move both of these items into your APPDATA folder and test. 

Business logic
`%APPDATA%\RAVE\XML\brat.xml`

Layer Files
`%APPDATA%\RAVE\Symbology\BRAT\*.lyr`

Once eveything is working on your computer, zip up your RAVE APPDATA folder and test it on another computer.

Review with @wally-mac and/or @joewheaton . If you all agree then send me a zip and I can issue a new RAVE release that includes your work. That way all future BRAT users will get your business logic and symbology without you having to copy files around etc.

## Fix BRAT Script

You will need to fix whatever script produces the BRAT project files so that they include correct file paths instead of the placeholder "f" and "p" currently being used.

**Comment by wally-mac** [comment]
Thanks @philipbaileynar and @banderson1618 for your hard work on getting BRAT working with RAVE.  As far as priorities go I think this is a high priority and I think we should "strike while the iron is HOT".  So, I say Braden go for it and keep me posted on how much time it's taking.

**Comment by philipbaileynar** [comment]
@banderson1618 you should **not** reference the layer files in the BRAT project file. It's fine that BRAT continues to produce them.

If the layer files contains generic symbology that is relevant to all BRAT projects then you can simply copy one of each layer type into your `%APPDATA%\RAVE\Symbology\BRAT%` folder and rename the file to match the symbology key in the business logic. In other words, these layer files could save you some time and be the source of your symbology rather than re-generating each symbology by hand.

**Comment by banderson1618** [comment]
Sounds good, thanks for the responsiveness, @philipbaileynar.

**Comment by joewheaton** [comment]
pyBRAT now is handled well in all versions of [RAVE](http://rave.riverscapes.xyz)
