### ISSUE TITLE
Railroad issue for Conflict Potential

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#20]
I am seeing a very low value "0", for the conflict potential that is ran for the stream network. Railroad seems to be the issue.
![image](https://user-images.githubusercontent.com/30604787/38154125-a0a313ee-342d-11e8-96da-239b3838db4b.png)

**Comment by bangen** [comment]
This issue was due to not correctly defining the distance from railroad (iPC_RR) attribute field type.  It was been fixed in release 3.0.6.

In resolving the issue, I also found that several segments in the network were duplicated.  I traced this back to the original NHD flowlines shapefile, which contained duplicate polylines.  Duplicate polylines in the network can raise issues in BRAT where only one of the polylines is properly attributed.  To circumvent this issue, I recommend running the 'Delete Identical' tool in ArcMap and selecting 'Shape' field.  Ideally this should be run before segmenting the network.  However, if you've already segmented your network you can run it before running any of the BRAT tools.
