### ISSUE TITLE
Conflict Potential Railroad

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#22]
I am still having issues with the BRAT conflict layer and I am seeing issues with this still occuring the following video describes my issue https://youtu.be/jH101pomnlo

**Comment by bangen** [comment]
This issue was due to:
1. **The zonal statistics tool in Arc does not calculate statistics for overlapping features** (in this case the BRAT buffers).  The way the zonal statistics tool handles overlapping features is inconsistent.  For example, in the case of 2 overlapping buffers (buffer A, buffer B), in one instance of running the tool statistics are correctly populated for buffer A while buffer B is skipped. A second run of the zonal stats tool could result in buffer B correctly populated while buffer A is skipped.
2. **Using 'flat' buffers**.  In BRAT we were using flat buffers for the purpose of looking at what is adjacent to each network segment without looking upstream/downstream.  However, in troubleshooting I discovered that there can be huge issues with how the flat buffers are created.  Essentially we end up with some really odd shaped buffers and instances where the buffers don't fall on the stream polyline segment.

I resolved the above issues in release 3.0.8 by:
1. Creating a function handle the zonal statistics calculation for overlapping buffers.  
2. Switching to round buffers instead of flat buffers.

You can see a detailed video [here.](https://youtu.be/tV0y_N3GckA)
