### ISSUE TITLE
Regression equation xml

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#228]
@banderson1618  I know that you just put out an updated xml file that you discussed in issue #181 but did you or could you include the addition of documenting the regression equations. This would be useful to see what was used for past runs and eliminate the hassle of finding new regression equations for projects already ran.

**Comment by banderson1618** [comment]
We did not implement that, but we absolutely could. We probably need to improve the method for adding regression equations, and this could be rolled into that.

**Comment by MatthewMeier** [comment]
@banderson1618 just checking up with you if this is purely a wish or something that we could implement soon. @wally-mac and I were just speaking about tasks today and I was inquiring?

**Comment by wally-mac** [comment]
This could be something we have the new techs work on.

**Comment by mhallerud** [comment]
@wally-mac @MatthewMeier @Albonicomt Hey everybody, just wanted to get some opinions on how to move forward with improving our method for specifying regression equations in the iHyd tool. @banderson1618 and I were discussing adding parameters so that users could enter coefficients for each model. The only problem I see is that this would enforce a rigid equation structure which could be limiting if the equation in mind does not fit said structure. The other option would be having users enter the full equation for each regression curve, but that could very easily lead to syntax errors in the code. Thoughts on either option, or other ideas?

**Comment by mhallerud** [comment]
For now I just added two optional fields in the tool for writing the equations to be included in the XML, but I can work on improving the functional equations in the code once we decide on the best way to go about accomplishing that.

**Comment by banderson1618** [comment]
Thanks for the input, @MatthewMeier.

I believe that Option 1 would make batch processing easier, not harder. Let's bring this up at the staff meeting on Tuesday and hammer out what this should look like.

**Comment by wally-mac** [comment]
@mhallerud what is the status of this ticket?

**Comment by mhallerud** [comment]
@wally-mac I put it on the back-burner due to the syntax concerns. I can go ahead and implement option 1 that @MatthewMeier laid out above though, it should not take long at all.

**Comment by MatthewMeier** [comment]
@mhallerud sounds good to me although I think it would be really helpful to enter an example of one into the help box so that users would run into less syntax errors.

**Comment by mhallerud** [comment]
@MatthewMeier No problem, I can look into that.
