### ISSUE TITLE
Failed to find Existing Veg Suitability Layer

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyBRAT#239]
1. Note that I'm using ArcGIS 10.4 with all the extensions.
1. Clicked on the **Step 1. BRAT Project Builder** tool.
1. I supplied all the inputs (all layers except ownership)
1. Click OK and got the following error.

![2018-11-29_155331](https://user-images.githubusercontent.com/8645379/49259680-3b27d680-f3ef-11e8-83c0-bd257d480ed3.png)

Note that I do appear to have the specified layer file. Could it be an ArcGIS version issue?

![2018-11-29_155630](https://user-images.githubusercontent.com/8645379/49259707-585ca500-f3ef-11e8-842c-784b3e078030.png)

**Comment by banderson1618** [comment]
This very well could be a problem with versioning, but it might also be a problem with applying symbology to vegetation rasters, which we've had problems with before.

In "BRATProject.py", from line 74 to line 86, the program calls the function `makeInputLayers()` a bunch of times. I'd recommend commenting out those calls, and seeing if that helps.

**Comment by banderson1618** [comment]
This issue may rear its head later on in the Layer Package Generator, since there is a similar function called there, but we can deal with that when we get there.

**Comment by philipbaileynar** [comment]
Perhaps the code is trying to apply a classification from a layer file that is either expecting a certain attribute/field that doesn't exist or the number of bins in the dataset that was used to generate the layer file is different from the target dataset to which it is being applied. Similar problems arrive when applying stretch renderers to datasets that possess a different range.

I commented out the lines you referred to and it broken further on regarding DEM symbolization. 

Then I skipped ahead to step 2 and the BRAT table and got overwhelmed at the prospect of having to browse to 20 inputs!

**Comment by banderson1618** [comment]
Hm... That's odd, we've never had a problem with applying symbology to DEMs. That does seem to imply a problem with your installation of ArcGIS, rather than a problem with the data. Unfortunately, since I can't replicate the bug on my computer, my ability to troubleshoot is limited.

A short term solution would be the following: in the `makeLayer()` function in "BRATProject.py", you can replace the line

```
    if symbology_layer:
        arcpy.ApplySymbologyFromLayer_management(new_layer, symbology_layer)
```

with

```
    if symbology_layer and isRaster:
        arcpy.ApplySymbologyFromLayer_management(new_layer, symbology_layer)
```

That should be on line 217-218. Unfortunately, this was before we consolidated the `makeLayer()` into a single function, so if you run into this problem again later on, you'll need to make that same change in that tool's copy of the `makeLayer()` function.
