### ISSUE TITLE
Zonal Stats implementation

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#243]
@mhallerud,
@wally-mac and I are ready to revisit the zonal stats that sara worked on earlier this year. It is an implementation that would correct some of the funky errors that happen when some of the calculations are made. @banderson1618 can fill you in on this a bit more on what the specific purposes are.
Here is some information that would be helpful to look at as your getting started on this...

- Why we needed to implement these changes #155 

- setting your pc up for the proper modules for the setup #185 (This also details some problems implementing this before)

The code was part of the branch that was implemented but there were some bugs to still work out and so we reverted back to the old methods so that we could get some products out for reports and workshops. This implementation was just pushed off not eliminated and needs to be revisited.

**Comment by mhallerud** [comment]
A few quick updates: 
- I ran into the same problems as @banderson1618 had previously with installing the rasterio dependency. All dependencies (raster, GDAL, fiona, shapely) seemed to download properly using wheel files, but rasterio would not load in Python. 
-Error#1 from importing rasterio: "ValueError: numpy.dtype size changed...".  This error seems to be due to rasterio being compiled with an earlier numpy version (see [stackexchange discussion](https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility)) and can be bypassed with `warnings.filterwarnings("ignore", message="numpy.dtype size changed")`. Note - I'm not sure if this breaks the rasterio module later since I couldn't get it to import. 
-Error#2: "ImportError: gdal_version could not be found". Looking at the rasterio [source code](https://github.com/mapbox/rasterio/tree/master/rasterio), gdal_version is defined in __base as `GDALVersionInfo("RELEASE_NAME")`. GDALVersionInfo() is housed in the gdal.h file reference and would not run by itself either. 
I fiddled with the last error a bit but am still stuck. I'm pretty sure it has something to do with the .h files not being connected /loaded to Python. I tried copying and pasting the .h files to other folders within the osgeo folder and GDALVersionInfo still could not be called.

**Comment by wally-mac** [comment]
I'm adding @bangen to the conversation. Sara, do you have any advice for Maggie (@mhallerud)?

**Comment by bangen** [comment]
@wally-mac @mhallerud I'll try a fresh install on my laptop.  I'm currently installing Arc 10.6 so might be a bit, but I'll get back with details once I get it set up.

**Comment by banderson1618** [comment]
@bangen were you able to make any progress on this front?

**Comment by wally-mac** [comment]
@joewheaton let me know that we do not have funding to pursue this at this time.  I'm closing this ticket.
