### ISSUE TITLE
What's the purpose of the file "metadata_description.py?

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#247]
I just noticed this file, and I'm not sure what it's for. It looks like it's a copy of BRAT_table.py, but it isn't referenced anywhere else in BRAT from what I can tell. Git blame says that it was created in commit e8a6d03, by @mhallerud.

**Comment by mhallerud** [comment]
That's my bad, Git picked up a few of my undocumented files earlier this week because they were in my local repository. I thought I corrected it, but apparently I missed one. Thanks for catching that. Metadata_description was just my working file for adding a description to the XML, so it can be deleted.

**Comment by banderson1618** [comment]
Makes sense, I'll delete it and push

**Comment by mhallerud** [comment]
Thanks and sorry about that.
