### ISSUE TITLE
Error running Layer Package Generator

### ISSUE THREAD

**Issue by mhallerud** [Riverscapes/pyBRAT#250]
@banderson1618 I ran into this error with the Layer Package Generator. The tool worked on another BRAT run and I double checked that all shapefiles and layers were present. I tried digging into the arcpy _management code, but it's not really helpful. Have you seen this before and have any suggestions?

![image](https://user-images.githubusercontent.com/43869036/50364157-03aed480-052c-11e9-9008-342b6123eaad.png)

**Comment by banderson1618** [comment]
Sorry for the long delay. If I had to guess, I'd say that you probably had
a broken layer that the tool tried to package. Pull the layers generated by
BRAT into Arc, and see if any of them have a red x and don't load.

**Comment by MatthewMeier** [comment]
Hey @banderson1618  I am getting the following error with the layer package generator. I believe that @mhallerud issue was an isolated situation but could you take a look at this one. 
![image](https://user-images.githubusercontent.com/30604787/50610653-f9c49400-0e90-11e9-8764-abdd67a244e0.png)
Here is the [data](https://usu.box.com/s/kytks31tz1ovj1a8mtdfkhek2ffyljp0).

**Comment by MatthewMeier** [comment]
No worries

**Comment by banderson1618** [comment]
I think I know what the problem is. You selected the `Outputs` folder as your input for the Layer Package Generator, but you should have selected `Output_##`  instead. It's expecting the latter, so it breaks when it can't find the right folders inside it. I'll add some error checking to make that more clear in the future. Does that make sense to you, @MatthewMeier?

**Comment by MatthewMeier** [comment]
@banderson1618 yes that makes sense. Thanks for the input
