### ISSUE TITLE
Changing "Data Validation" to be more useful to managers

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#255]
@wally-mac recently asked me to make the Data Capture Validation more friendly for managers to use. He suggested renaming it and adding a field that records the ratio of observed dam density to historic capacity, and another that records the ratio of observed dam density to existing capacity. He also suggested renaming it. Those two field will not be hard to implement, but I would invite @MatthewMeier, @mhallerud, @BrittGraham, and @bangen to post their suggestions for a new name in this issue, as well as suggestions for other useful fields.

**Comment by mhallerud** [comment]
Since the primary purpose of the tool is to validate/verify the BRAT model by comparing with dam data, I think "Model Validation" or "BRAT Validation" would capture that purpose and be more self-explanatory. I'll think more for the ratio of observed dam density to historic capacity- right now I'm only coming up with generic names and nothing more biologically meaningful.

**Comment by MatthewMeier** [comment]
Right now there is a ratio for the observed dams to existing capacity but I do think that it would be interesting to see the historic. This would still work out because there would be even higher predictions with the historic capacity than the existing should. It would be a good comparison.
Right now I do not have any other useful fields to add, However making this automated for the excel sheet would be useful. @banderson1618 and @mhallerud we have discussed this but if you need some insights let me know.
As for names for the Data Validation I would say "Model vs Census Validation"

**Comment by mhallerud** [comment]
@MatthewMeier I've started on adding the electivity index and related fields (per #245). Planning on finishing that up later this week or perhaps early next week depending on when I get those Idaho BRAT models done and a few dam surveys in. Let me know if it's more urgent and I'll plan to keep you updated once I get a baseline output to see if anything else should be added.

**Comment by MatthewMeier** [comment]
@mhallerud send me an example when you have one. preferably run a practice run on the north fork Burnt or John Day so that we have something to compare it against. Don't change any of the data for those projects on box though. They are getting buttoned up and things staying how they are is essential.
