### ISSUE TITLE
ImportError: no module named _Internal thrown when using pip install.....

### ISSUE THREAD

**Issue by andrewsechrist100** [Riverscapes/pyBRAT#265]
Hi,
    I am just trying to set up my system to begin initiating a BRAT model. I have experience with ArcGIS, but not with using the Command Prompt. So, I am getting stonewalled before I even get started! am new to using. I have 2.7.15 installd, but am not sure how to determine if other installations are causing problems (screenshot attached). I receive the exception shown in the Title when I run "pip install --upgrade pip" or "pip install scikit-fuzzy" (screenshot attached). I have spent 10-12 hours trying to understand this through stackexchange, without any luck. I do seem to have 2 Scripts files on my system, as shown in "Location 1" screenshot. Thank you,  Andy
PS Please let me know what format changes or inclusions you want to see in future question submissions from me rather than ignoring me like StackExchange does ;)! I am a newbie, but pick things up quickly. 

![pip capture1](
![pip capture2](https://user-images.githubusercontent.com/48166366/53771327-d37a9f00-3ea7-11e9-85f9-73e014949825.JPG)
![pip capture3](https://user-images.githubusercontent.com/48166366/53771336-d5dcf900-3ea7-11e9-99d7-c8d973fa5004.JPG)
![applications](https://user-images.githubusercontent.com/48166366/53771341-d83f5300-3ea7-11e9-8aa4-c0ecfa976fe2.JPG)
![location 1](https://user-images.githubusercontent.com/48166366/53771344-daa1ad00-3ea7-11e9-9c12-22411735ff13.JPG)
![location 2](https://user-images.githubusercontent.com/48166366/53771347-dc6b7080-3ea7-11e9-830a-cbae5a3a279a.JPG)

https://user-images.githubusercontent.com/48166366/53771318-c6f64680-3ea7-11e9-82b2-0b40b5cb349f.JPG)

**Comment by banderson1618** [comment]
Hey Andy,

It looks like you tried to use some things that were specifically for Linux command line, which is why the commands in your second screenshot are failing. "Sudo" is not a valid command in Windows, and $ is only used to mark the beginning of command line input on Linux. 

It looks like you have python installed and added to your system variables. It's possible you also have pip in your system variables. Type in `pip --version` to verify whether or not that's the case. If you get a version number, you're all good. Otherwise, we're going to have to run pip from the file in the Scripts folder of your Python installation.

Since you have python in your system variables, the following command should work to upgrade pip: `python -m pip install --upgrade pip`. Type that in to your command line, and let me know what shows up.

**Comment by andrewsechrist100** [comment]
Hi Braden,
     Thank you very much for getting back to me so quickly! I am running BRAT as a initial step in my thesis project for my MS and want to have it completed well before the summer field season (when I will conduct ground-truthing of the output). So, I really appreciate your timeliness. It seems as though I solved my current issues by uninstalling and reinstalling ArcGIS and uninstalling some Python hangons (don't know if that had an effect or not). I have attached some screenshots so you can see the results.      I am sure I will have questions as I work through the model, and in fact have a couple now. After looking at the Landfire rasters for existing and historical vegetation, I see that the Value fields do not match up. I did find a "glossary" for the integers in the Value fields for the 140bps, which I have attached. The integers in the Value field for this only go up to around 2,600 and those in the 140 bps attribute table only go to around 2,100, so I'm guessing that Excel file is accurate? The integers in the 140evt attribute table range from around 3,000 to 3,900 or so. So, will this discrepancy cause any issues later? Also, which field is generally best to use to base the classification off for the 140evt table? Some Of the wording in some of the fields is a bit confusing relative to each other in the same record (at least for me). And, would it be OK to send you Excel file derived from my bps and evt tables for inspection once I have them completed?      Finally, are there more tutorial videos on the BRAT webpage? The only ones I have found ar for creating layer packages? Cheers,
Andy     
    On Wednesday, March 6, 2019, 6:40:41 PM CST, Braden Anderson <notifications@github.com> wrote:  
 
 
Hey Andy,

It looks like you tried to use some things that were specifically for Linux command line, which is why the commands in your second screenshot are failing. "Sudo" is not a valid command in Windows, and $ is only used to mark the beginning of command line input on Linux.

It looks like you have python installed and added to your system variables. It's possible you also have pip in your system variables. Type in pip --version to verify whether or not that's the case. If you get a version number, you're all good. Otherwise, we're going to have to run pip from the file in the Scripts folder of your Python installation.

Since you have python in your system variables, the following command should work to upgrade pip: python -m pip install --upgrade pip. Type that in to your command line, and let me know what shows up.

**Comment by banderson1618** [comment]
Hey Andy,

I can't see your attachments, because GitHub can't automatically include the attachments of an email that you send to a thread. You'll have to come to the GitHub website and include those images in your message, sorry.

As for tutorials, preprocessing data isn't really my specialty here. There are tutorials on running BRAT on our website, the first step of which is linked [here](http://brat.riverscapes.xyz/Documentation/Tutorials/StepByStep/1-InputData.html). Hopefully that helps. If not, I'll tag some co-workers to see if they have insight.

**Comment by andrewsechrist100** [comment]
Sorry about that Braden. I have looked through the website forward from the page in the link you provided, but have not seen other videos than for the Layer Package creation. Am I missing something? I would appreciate help with the preprocessing part of running the model (as I described in my reply above). 
![i have the tools now](https://user-images.githubusercontent.com/48166366/54005218-3f663d00-411e-11e9-8452-fc80197e8364.JPG)
![140bps](https://user-images.githubusercontent.com/48166366/54005220-41c89700-411e-11e9-98d6-7ab36ed23f94.JPG)
![140evt](https://user-images.githubusercontent.com/48166366/54005224-43925a80-411e-11e9-9e32-2763ed84da0d.JPG)
[Glossary for bps11042014.xlsx](https://github.com/Riverscapes/pyBRAT/files/2944255/Glossary.for.bps11042014.xlsx)

**Comment by banderson1618** [comment]
There aren't more videos, but the page I've linked you is the first step in a step-by-step walkthrough on how to run BRAT. The step after that talks about preprocessing the vegetation layers, I suggest you look at that [here](http://brat.riverscapes.xyz/Documentation/Tutorials/StepByStep/2-Preprocessing). The value fields don't matter, since we use a custom field called "VEG_CODE". You will have to look at our criteria for different values in VEG_CODE and decide what best fits your watershed(s) vegetation layers, since there is too much variety in vegetation data for us to create a standard that works outside of where we normally work.

**Comment by andrewsechrist100** [comment]
Hi Braden,
    Thank you for your input on the Value field differences. I will try posting more specific questions should I run into difficulty in the classification of the VEG_CODE field. Thanks for your help thus far,
Andy    On Friday, March 8, 2019, 11:41:41 AM CST, Braden Anderson <notifications@github.com> wrote:  
 
 
There aren't more videos, but the page I've linked you is the first step in a step-by-step walkthrough on how to run BRAT. The step after that talks about preprocessing the vegetation layers, I suggest you look at that here. The value fields don't matter, since we use a custom field called "VEG_CODE". You will have to look at our criteria for different values in VEG_CODE and decide what best fits your watershed(s) vegetation layers, since there is too much variety in vegetation data for us to create a standard that works outside of where we normally work.

**Comment by andrewsechrist100** [comment]
Hi Braden,
     I have another issue posted to the site, but this one can be closed if you'd like. Thanks again,
Andy
    On Thursday, March 7, 2019, 4:54:29 PM CST, Braden Anderson <notifications@github.com> wrote:  
 
 
Hey Andy,

I can't see your attachments, because GitHub can't automatically include the attachments of an email that you send to a thread. You'll have to come to the GitHub website and include those images in your message, sorry.

As for tutorials, preprocessing data isn't really my specialty here. There are tutorials on running BRAT on our website, the first step of which is linked here. Hopefully that helps. If not, I'll tag some co-workers to see if they have insight.
