### ISSUE TITLE
multiple watersheds

### ISSUE THREAD

**Issue by andrewsechrist100** [Riverscapes/pyBRAT#267]
Hi BRAT tam,

    I still have questions about using Python tools from the Supporting Tools folder (my previous Issue
 submission), but wanted to ask this question as well. I am going to attempt to model South Dakota east
 of the Missouri River. The total number of watersheds required for this is 23, including fringe watersheds 
that are shared between states. Is it best to merge and clip data and run the resulting shapefile through 
the tools or do I need to run all the tools separately for each watershed? Or, is it best to merge but not 
clip, as this gets rid of huge chunks of some shared watersheds? Thanks and Cheers,

Andy

**Comment by banderson1618** [comment]
Because BRAT is calculated on a reach-by-reach basis, it shouldn't make any difference whether you merge the data and run it in one go or run each smaller watershed separately. You might run into memory issues when running HUC 6s and bigger, because we need to make a Zonal Stats table and ArcGIS can only use 4 GBs of RAM, but other than that, do whatever is easiest for you.
