### ISSUE TITLE
How Did you pick the Idaho UTM Zone?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyBRAT#292]
The state of Idaho roughly [spans UTM zones 11 and 12](http://www.wa6otp.com/fig44.gif). Did you use one or two zones for the Idaho BRAT project? And if you picked one, what criteria did you use to decide which one to use?

**Comment by wally-mac** [comment]
The Idaho Department of Water Resources uses the Idaho Transverse Mercator Projection which is also recommended by the Idaho Technology Authority for state-wide data.  It was built specifically to handle the issue of the state being split into 2 UTM zones.  So we used that for BRAT instead of 2 UTM zones.
