### ISSUE TITLE
Unable to install BRAT with ArcGIS Pro (2.0)

### ISSUE THREAD

**Issue by mahmuda22** [Riverscapes/pyBRAT#302]
Hi,
I am using ArcGIS pro for last couple of months. I am not very familiar with ArcGIS Pro. I am trying to install BRAT (Beaver Restoration Assessment Tool) in ArcGIS Pro. I have installed the scikit-fuzzy python module and xlsxwriter module. Is not BRAT compatible with ArcGIS Pro? Any help would be appreciated. 

![image](https://user-images.githubusercontent.com/65062852/81467112-131fd380-919c-11ea-91a4-dc8aff922825.png)

**Comment by mhallerud** [comment]
@mahmuda22 Apologies for the late response. To be honest, I am not sure if pyBRAT is compatible with ArcGIS pro. The current version was built in ArcMap Desktop 10.6.1 (also running in 10.7.1), so it should work if you have a Desktop ArcMap license available. Otherwise it is hard to know what's going on without any errors. If you check syntax on the toolbox (assuming this is an option in Pro), does it specify what line is problematic?

**Comment by joewheaton** [comment]
pyBRAT is not compatible with ArcGIS Pro. The good news is, if you have a ArcGIS Pro license, you can concurrently install ArcMap 10.x simultaneously.
