### ISSUE TITLE
Data Request: Unedited BRAT Valley Bottoms

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#37]
Chris Murphy, Wetland/Riparian Ecologist with Idaho Department of Fish and Game wants to use the unedited valley bottoms, feeding the BRAT tool.  We will revisit this when we complete valley bottoms. @bangen I'm making you aware of this because it does suggest that people are going to want to use the valley bottoms we produce so the better we can make the with minimal edit the better.

**Comment by bangen** [comment]
@joewheaton I've shared this with previously with Wally but want to bring you in on the discussion.  I played around with implementing a different approach to deriving valley bottoms.  My main motivation was to develop an approach that would require less manually editing.  

Here's a [video](https://youtu.be/RbBvu7FA3XM) I put together for Wally.  I attached some kmz files of the output.

In a nutshell the approach creates a detrended DEM and then fills it to create the valley bottom polygon. 
 It is a marriage between Beechie's 2013 WRR paper and the RBT detrending workflow.  General steps are:

1.  Segment flowline network into 200 meter reaches
2.  Create midpoints for each reach
3.  Get min Z within 60 m buffer of each midpoint
4.  Create trend surface from min Z reach midpoints.  I found using idw of 12 points and power of 2 produced decent trend surface while minimizing computational time. 
5. Smooth trend surface (used 200 m since that was our ~ point spacing)
6. Subtract smoothed trend surface from DEM to get detrended DEM
7. Fill detrended DEM
8. Optional: Remove areas with higher DEM slope (20 degrees)
9. Apply minimum buffer to enforce valley bottom on segments that didn't meet fill threshold criteria

This approach works really, really well in the main valley of the watershed.  Where it struggles more so it seems to over-predict in some instance higher up in the watershed or in really low sloping areas.

If this approach seems worthwhile to test out in the future some things that would be good to test:

- limiting interpolation distance
- different approaches to pulling off min Z (e.g., use reach end point rather than midpoint, buffer entire reach)
- which parts of stream network to include (e.g., just perennial; just perennial and intermittent; all perennial; intermittent and ephemeral)

 
[Truckee_ValleyBottom_Fill6.zip](https://github.com/Riverscapes/pyBRAT/files/2020802/Truckee_ValleyBottom_Fill6.zip)
[Truckee_ValleyBottom_Fill8.zip](https://github.com/Riverscapes/pyBRAT/files/2020803/Truckee_ValleyBottom_Fill8.zip)
[Truckee_VBET_SegementScale.zip](https://github.com/Riverscapes/pyBRAT/files/2020804/Truckee_VBET_SegementScale.zip)
[Lemhi_ValleyBottom_Fill8.zip](https://github.com/Riverscapes/pyBRAT/files/2020810/Lemhi_ValleyBottom_Fill8.zip)
[Lemhi_VBET_SegementScale.zip](https://github.com/Riverscapes/pyBRAT/files/2020811/Lemhi_VBET_SegementScale.zip)

**Comment by joewheaton** [comment]
Hi @bangen. My initial impression is we don't want a new valley bottom tool at this point, even though what you did here could be better. It doesn't surprise me that it works well in the mainstems (but Jordan's VBET is not that bad), and that this approach falls apart. Please don't work on this anymore at this point. There are good ideas here, but nothing that is a priority right now (in my opinion). I'm flagging this as future development ideas.

**Comment by joewheaton** [comment]
@wally-mac I'm removing the analysis label, as I think this is getting done without these changes.

**Comment by joewheaton** [comment]
This is a potential future enhancement.... Shelved for now.
