### ISSUE TITLE
Best Practice for Making Releases of Software to Users (NOT PROGRAMMERS)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#4]
@MattReimer  and @philipbaileynar ,  We need your professional guidance here.  GIT seems great at keeping track of all our changes to code and documenting that transparently to serve programmers and developers that may use the code.  I've noticed the concept of a 'release', which I asked about in #2.  My question is, what is the best way to package up just the file(s) that constitute a 'download' of the software for an *idiot*  end user, that doesn't know anything about GIT and certainly doesn't need all the sourcecode? Do 'releases' just make a snapshot of the whole repo, or do they allow the release to select just the files that the user needs (e.g. an `*.addin` or a `*.zip` or a `*.exe` if there is an installer or something)? Do you have some examples you can point us to and some suggestions of best practice or at least options? Is it as simple as just packaging up what you want and organizing them in a different 'releases' folder? Or do we have to put them on an external site (e.g. in our AWS S3 buckets set up as file servers)?

Thanks for help!

**Comment by philipbaileynar** [comment]
I wasn't aware of the ability to upload binaries for GH releases. That's potentially very useful!

Unfortunately, the answer is different depending on the technology...

## Interpreted Code (Python, R, MatLab, JavaScript, HTML, Node.js)

Most interpreted code simply gets downloaded and run. It does not get packaged. These types of products should simply be "tagged" with a version number at each release. The GitHub release tool appears to extent the native git tag capability with some extra information that might be useful. I haven't used it and simply rely on tags.

For interpreted code I would not produce zip archives or any other type of package. It's redundant given that the code is in git. Zipping just increases the potential for confusion.

## Compiled Code (C++, C#, VB)

You should keep a set of binaries for each release of compiled code. Each set of binaries should include the full suite of files required at deployment. For example, our Rasterman.exe binary ships with some Qt binaries that we have compiled and are required to run the program. Also, we archive multiple sets of rasterman binaries, one for each architecture (32 and 64 bit) and operating system (MaxOS, *nix, Windows).

You absolutely want to avoid storing binaries in the git repo if at all possible. git can't handle partial binary file changes the way it can with text code files, and so each change requires a full copy of each file. They will bloat the repo, slowing it down for everyone - even if they just want to do a fetch.

We use Amazon S3 for this purpose. I would be interested in learning more about the GitHub release feature that @joewheaton mentioned, and finding out where precisely the attached binaries are stored. I'm suspicious of black boxes where I can't get at the files directly. 

## Tagging

A comment about tagging. This is the primary way of demarking the place in a repo commit history that captures a specific release. Each product needs a system of naming its releases and tags. The major, minor, revision standard is a good start, although there might be exceptions. 

Note that git tags need to be **pushed** to the remote. Otherwise they only reside on the local copy of the repo where they were created. Took me a while to realize this.

Note that even if you didn't use the GitHub feature to create "releases", that GitHub still seems to recognize tags and present them as releases. Here's the [CHaMP Workbench release history](https://github.com/NorthArrowResearch/champ-workbench/releases). I've tagged this repo but never actually used the the git release feature.

**Comment by joewheaton** [comment]
Okay @philipbaileynar. I made a [release of our old version 2 Matlab stuff](https://github.com/Riverscapes/matBRAT/releases/tag/v2.03) over in that repo.  Its pretty handy. It allows you to upload a zip file or binaries, package it up and flag it as whatever version it is. Pretty nice. It also allows you to identify the 'Latest Release' and make 'Beta Releases'.

**Comment by joewheaton** [comment]
This question is answered. Assigning @jtgilbert #5 and closing this thread.
