### ISSUE TITLE
Does pyBRAT Have Too Many Steps?

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#57]
# Does pyBRAT Have Too Many Steps?
Right now, BRAT has nine steps, but many of them simply modify the output of the step before them, and do not take much time to run. It seems to me that some of them could be run together, so that the tool is less arcane to run for first time users. I will lay out some of the tools that I think could be consolidated below.

## The Project Builder could be implemented in the BRAT Table Tool
This would probably be the most work out of any that I'm suggesting, but it should be possible to have the BRAT Table tool create the project folder entirely on its own. This would be a significant improvement for when the technician is only using one input per category, and would allow the technician to try a new input without having to re-run the project builder. Running the BRAT Table tool would dynamically add an folder to the relevant input if it detected that the input has not been used before.

## The BRAT Braid Handler could be moved to a Supporting Tools section
Currently, it seems a bit weird to put the Braid Handler as a full step in the process, given that it's an optional tool only meant to be used in a minority of cases. Organizationally, it makes more sense to me to put it in the "Supporting Tools" folder, since it is a supporting tool, not a full step.

## iHyd and Vegetation attributes could be added in the BRAT Table Tool
The iHyd Streamflow Attributes and Vegetation Dam Capacity Model tools both take the output of the Table Tool and derive attributes from the data already there. Why not derive these attributes automatically when running the BRAT Table Tool? This would be extremely easy to implement, and would streamline the process of running the tool immensely.

Disclaimer: it's possible that there is some manual editing necessary between running the Table tool and the iHyd and Vegetation tools that I don't know about. Since I've mostly been working on new features and fixing bugs, I don't know as much as I would like to about the process of running the tool like a technician needs to. If that's the case for one or both of these tools, that's a good reason to not consolidate in this way. Otherwise, however, I don't see a reason to leave them as separate from the Table tool.

## The Combined Dam Capacity Model, Conflict Potential, Conservation and Restoration Model, and Summary Report could all be consolidated
All of these tools follow one after the other. Although they require some inputs besides the output of the previous tool, we could easily collect these inputs all at once and run the tools automatically one after the other.

The disclaimer from the above section applies just as much to this section.

## Summary
I believe that the tool could be simplified to two or three steps (depending on how you count the Braid Handler). Hypothetically, it could even be a single step, but it makes sense to retain the ability to check the intermediates before creating the output, so two steps seems reasonable to me.

@joewheaton, @wally-mac, @MatthewMeier, @Albonicomt, and @bangen, what do you all think of these ideas? It's very possible that I'm missing the reasons for why the tools are split up like they are, or that implementing changes like this are a low priority, so feedback would be appreciate.

**Comment by joewheaton** [comment]
@banderson1618 I really like how you're thinking critically about how the tool is working. Your timing is good as @bangen and @wally-mac are just discussing this. Ironically, I think that we actually want to go the opposite direction to what you're suggesting (i.e. add more steps instead of less). Your suggestion of streamlining steps makes sense if we stick with and assume there is a wizard like, linear workflow (e.g. the [current documentation](http://brat.riverscapes.xyz/Documentation/) only envisions pyBRAT as a series of nine steps.  Here's what I want us to focus on instead:
1. Reimagining pyBRAT similar to GCD with a Project, and a bunch of optional commands 
2. Stripping out each 'step' and re-thinking it as a 'command' that has a more generic input requirements, and produces a specific output. If command is run in context of pyBRAT project, housekeeping is easier and we get it from what would have previously been envisioned as a 'step'.
3. Trying to genericize analyses and commands within BRAT
4. Do a better job of allowing and tracking multiple realizations of all inputs, all intermediates and outputs within a pyBRAT project) 
5. Take your specific suggestions above and produce them as 'commands' that streamline and combine multiple steps to populate a project. 

Take a close look at how [GCD](http://gcd.riverscapes.xyz) works for some ideas about all this.

We'll regroup next-week on this.
