### ISSUE TITLE
BRAT Layer Package As Step 10

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#84]
Right now the layer package is part of the 'Summary Report' tool.  IMO, this should be pulled out into its own step.

**Comment by bangen** [comment]
Also, currently the beaver dam shapefile is optional, but the validation output is required.  If we split the beaver dam validation and layer package into separate steps (as I'm recommending) then all relevant arguments will be required.  @banderson1618 if you decide it's best to retain these in a single step/tool make the output validation shapefile argument optional.

**Comment by bangen** [comment]
Just to clarify further, the reason I'm flagging the above is bc I simply want to make a layer package and don't have any validation data.  So if there's something I'm missing (i.e., there's a way to do this) let me know.

**Comment by banderson1618** [comment]
Regardless of whether or not you have beaver dam data, you should run the Summary Report, because it creates fields that aren't based on beaver dam data. The fields that it makes here are the basis of two of the layers that go into the layer package (the "Conflict_Potential" layer and the "Beaver_Management_Zones" layer).

If you wanted, we can move the creation of those fields and layers to Step 8 in BRAT, so that the Summary Report only produces beaver dam related fields. As Matt originally pitched it to me, they were a part of the summary report, but it doesn't have to stay like that.

**Comment by banderson1618** [comment]
Also, we can move the layer package generator to its own tool. It shouldn't be hard at all, with how I've structured the code. I'm working on a thorny issue right now, but when I wrap that up, it shouldn't take long.

**Comment by banderson1618** [comment]
@bangen, let me know what you think, I'd like to get your input before I change the code.

**Comment by joewheaton** [comment]
I DON'T think we should label this as Step 10, unless it is in the 'typical BRAT workflow' steps: http://brat.riverscapes.xyz/Documentation/Tutorials/StepByStep/. Please recall #57 discussion...
