### ISSUE TITLE
The Layer Package Generator has been split off into its own tool

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#85]
This should make it easier and clearer to use.

**Comment by wally-mac** [comment]
Great idea.  How is this coming along?

**Comment by banderson1618** [comment]
This is already in the code, I just forgot to close the issue. Thanks for the reminder!

**Comment by joewheaton** [comment]
Nice one @banderson1618. Before closing this, we should make sure there is a *.md documentation page on this command. It should minimally have a description of command, what are required vs. optional inputs, what paramaters, and description of outputs. Ideally, it also has a short YouTube video with its documentation. When this issue is closed, provide link to that page. @wally-mac, this doesn't mean that @banderson1618 needs to be the one to the documentation, but we should get in the habit on new commands of making sure that updates are also made to help documentation concurrently. If simpler to split these into their own issues, fine...

Thanks!
