### ISSUE TITLE
pyBRAT could use some automated testing

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#95]
My work for the "Segment By Roads" Issue #66 introduced a bug to pyBRAT, where split reaches had the same ReachID. This was causing problems with the dictionary join, leading to the two segments being assigned the same attributes. Unfortunately, I didn't catch it. @bangen was the one who pointed it out to me a couple days ago. She mentioned that we should do more testing/validating before we push code, which I agree with.

One of the best ways to increase how much testing we do would be to automate some of it. For example, we could have a function that runs at the end of running the BRAT Table tool that checks if each ReachID is unique. If it finds two reaches that have the same ReachID, it throws an error. This takes the burden off of the programmer to notice when something's wrong, and allows for a more thorough and consistent testing process.

@wally-mac, @joewheaton, @bangen, @MatthewMeier, @Albonicomt, let me know if you can think of common signs of a bug that should be automatically tested.

**Comment by wally-mac** [comment]
Excellent idea.

**Comment by joewheaton** [comment]
Great idea.... Maybe ask @MattReimer about some of the unit-code testing he implements in GCD that he now runs before pushing out releases. I've got no problems with commits that throw up unexpected bugs. That's all par for course.

**Comment by MattReimer** [comment]
It's a big topic but I'll post a few hints that should get you started. 

In order to do unit testing you need good **units**. When you start writing tests you begin to realize that the most important part of it is to write code that's actually testable.

* Your functions should be small enough that they only do one thing at a time. If you've got multiple loops inside your functions it gets out of hand really fast. Ask yourself if you can split it up to make it easier to test.
* [Pure functions](https://www.sitepoint.com/functional-programming-pure-functions/) are best and it's a good practice to write pure whenever you can. Side effects are nasty things that can cause a lot of grief. 

GCD is written in C# so that's what all our unit tests are going to be written in. I doubt they'll be too helpful to working in python but [here they are anyway](https://github.com/Riverscapes/gcd/tree/master/GCDConsoleTest).

For python the [Unittest (or maybe Unittest2) library](https://docs.python.org/2/library/unittest.html) is definitely adequate for what you need. I wouldn't get any fancier than that because you want your tests to be as simple as humanly possible or you won't use them. [Pycharm hooks in really well to these libraries](https://confluence.jetbrains.com/display/PYH/Creating+and+running+a+Python+unit+test), if that's what you're using, so you can automate test running.

[Here's a great article about unit testing in python to get you started.](http://docs.python-guide.org/en/latest/writing/tests/)

Some general guidelines I've learned the hard way:

* Starting from scratch on a big code base is scary. Test the hard stuff and the things everything else uses first. Leave self-evident functions for last. Life's too short and there's enough other shit that needs doing.
* Don't test lower-level functions at higher levels. If `FuncB()` uses `FuncA` test `FuncA` separately. Don't repeat the test of `FuncA()` inside `FuncB()`. `FuncB`'s test should only be about what it does on its own.
* The bare minimum is this:  
    * 1 success case, 
    * 1 failure case (i.e. does it fail the way I'd expect) and 
     * as many edge cases as you can (big numbers, little numbers, NaN, infinities etc). 

Then, whenever you find a bug:

1. Write a test and make sure it fails
2. Fix the bug
3. Show the test passing

Gradually your test base will grow and you'll get a heads-up when something you change breaks something else in the code.

**Comment by banderson1618** [comment]
I'm glad you pointed me towards that article, it's good to have an intro to a concept that's slightly more readable than straight function documentation. This is all really good advice, thanks for the primer!

**Comment by banderson1618** [comment]
@MattReimer, what's the best way to unit test functions that take a shape file or a raster file as input? I've read that unit tests should be entirely self-contained, but I'm not sure how to implement that when a file path is a required input. Does it make sense to make the file you need in the unit testing class, or is this one of those rules that should be bent sometimes?

**Comment by MattReimer** [comment]
All rules are meant to be broken but these kinds of questions illustrate why we need to split functions up. Ask yourself "what is this function actually doing?". IF the answer is "Many things" split the function.

Without seeing the code myself or knowing what it does what I would do in very vague terms:

1. `Function A()` Load a shapefile and pull the fields, geometry etc into dictionaries. This should be easy to test. 
    * **Function A, Test 1**: Does the function open the file correctly?
    * **Function A, Test 2**: Does the function bail appropriately when the file is lost or not found?
    * **Function A, Test 3**: Does the function import all the geometry and fields correctly into dictionaries?
    * **Function A, Test 4**: .... etc.
2. `Function B()` takes either the full dictionary or just some of the values and **_does something_** with them and returns a result

Taking this strategy allows you to separate your concerns. Testing things like opening a file and working with the shapefiles spec are very different from testing the math of some math-y field calculation so you want your tests and, therefore also your functions to be separate.

Sorry if this all sounds a bit pedantic.

**Comment by banderson1618** [comment]
It doesn't sound pedantic, so no worries on that front. I think I might be thinking of tests the wrong way, because I was concerned about having to hardcode a path to a file, and it sounds like that's fine in tests. I appreciate your responsiveness, @MattReimer, it's been good to learn about this. Thanks!

**Comment by banderson1618** [comment]
Will do.

**Comment by wally-mac** [comment]
@banderson1618 , what is the status on this?

**Comment by joewheaton** [comment]
This was incorporated into 3.x
